# Generated by Django 5.1.6 on 2025-02-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
