# Generated by Django 5.1.6 on 2025-02-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
