# Generated by Django 5.1.6 on 2025-02-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
